#
# Name: makefile
# Author: Courtney Mueller
# Date: 9 / 6 / 2022
# Purpose: this is a makefile to compile and run lab3
#

all:	lab3

lab3:	symtable.c symtable.h
		gcc -o lab3 symtable.c

run:	lab3
		./lab3
